@startuml
'https://plantuml.com/class-diagram

class Game <<(M, blue)module>>
{
    +router:ExpressRouter
    +<<GET>> playGame(request:HttpRequest, response:HttpResponse):void
    +<<POST>> publishScore(request:HttpRequest, response:HttpResponse):void
    +<<PUT>> setQuestCompleted(request:HttpRequest, response:HttpResponse):void
    +<<GET>> getLeaderboard(request:HttpRequest, response:HttpResponse):void
}

@enduml
